### ISSUE TITLE
Disable basic completions

### ISSUE THREAD

**Issue by PrestonKnopp** [neikeq/atom-autocomplete-gdscript#1]
Hey, this is awesome!  :D I downloaded and compiled it and it works nicely!

I did notice that it's excluding both lang-gdscript and autocomplete+ default completions and I don't think you want to exclude autocomplete+ default completions (maybe that's just me), but I added some config that allows you to disable the lang-gdscript completions.

If you want, add `atom.config.set('lang-gdscript.disableBasicCompletions', true)` in your code and then you won't need to exclude lower completions.

Hope this helps!

**Comment by PrestonKnopp** [comment]
I'm also really excited about the completion service. I would like to utilize it for a vim plugin one day!

**Comment by neikeq** [comment]
Thanks! Now in the package settings there is the possibility to **Include all**, **Exclude all** or to **Exclude lang-gdscript only** lower priority suggestions.
